on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: $
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        version: 12
    - run: pip3 install -r requirements.txt
