# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
# Trigger the workflow on push request,
  push:
    branches:
      - main
      - features/*
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
    - run: pip3 install -r requirements.txt
